encyclopedia/urls.py
from django.urls import path

from . import views

app_name="wiki_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("wiki/<str:title>/", views.title, name="title"),
    path("create/", views.create, name="create"),
    path("edit/<str:title>/", views.edit, name="edit"),
    path("random/", views.random, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls", namespace='home')),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from random import randint
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django import forms
import markdown2
from . import util


class SearchFrom(forms.Form):
    search_q = forms.CharField(label="", widget=forms.TextInput(attrs={"class": "form-control p-2 mb-4", "placeholder": "Search Encyclopedia", "action":"{% url 'wiki_app:search' %}", "method":"post"}))

class CreateForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={"class": "border border-primary-subtle row rounded p-2 mt-2 mb-4 ms-2", 'size':'50', "placeholder": "Search Encyclopedia", "method":"POST"}))
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "border border-primary-subtle rounded row p-2 mt-2 mb-4 ms-2", "cols": "100", "rows": "20", "placeholder": "Search Encyclopedia", "action":"{% url 'wiki_app:create' %}", "method":"POST"}))

class UpdateForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "border border-primary-subtle rounded row p-2 mt-2 mb-4 ms-2", "cols": "100", "rows": "20", "placeholder": "Search Encyclopedia", "action":"{% url 'wiki_app:create' %}", "method":"POST"}))

def index(request):
    return render(request, "encyclopedia/index.html", {
    "entries": util.list_entries(),
    "search_form": SearchFrom()
    })

def title(request, title):
    content = util.get_entry(title)

    if content == None:
        return title_error(request, title)
    
    content_html = markdown2.markdown(content) 

    return render(request, "encyclopedia/title.html", {
        "title": title,
        "content": content_html,
    })

def title_error(request, title):
    return render(request, "encyclopedia/title_error.html", {
        "title": title,
    })

def search(request):
    if request.method == "POST":
        form = SearchFrom(request.POST)
        if form.is_valid():
            query = form.cleaned_data["search_q"]
            entries = util.list_entries()
            matches = [s for s in entries if query.lower() in s.lower()]
            
            if query in entries:
                return HttpResponseRedirect(f"/wiki/{query}")
            elif len(matches) > 0:
                return render(request, "encyclopedia/search_results.html", {
                    "query": query,
                    "matches": matches,
                })
            else:
                return render(request, "encyclopedia/no_search_results.html", {
                    "query": query,
                })
        else:
            print("invalid form")
            return render(request, "encyclopedia/search_error.html")
    else:
        return HttpResponseRedirect(reverse("wiki_app:index"))
    
def create(request):
    if request.method == "POST":
        create_form = CreateForm(request.POST)

        if create_form.is_valid():
            data = create_form.cleaned_data
            title = data["title"]
            if title in util.list_entries():
                return render(request, "encyclopedia/create_error.html", {
                    "status": "exists",
                    "title": title,
                })
            util.save_entry(data["title"], data["content"])
            return redirect(f"/wiki/{data['title']}")
        else:
            return render(request, "encyclopedia/create_error.html", {
                "status": "invalid"
            })

    else:
        return render(request, "encyclopedia/create.html", {
            "create_form": CreateForm()
        })

def edit(request, title):
    if request.method == "POST":
        update_form = UpdateForm(request.POST)

        if update_form.is_valid():
            data = update_form.cleaned_data
            util.save_entry(title, data["content"])
            return redirect(f"/wiki/{title}")
        else:
            return render(request, "encyclopedia/create_error.html", {
                "status": "invalid"
            })
    else:
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "update_form": UpdateForm(initial={"content": content})
        })

def random(request):
    entries = util.list_entries()
    i = randint(0, len(entries)-1)
    random_entry = entries[i]
    return redirect(f"/wiki/{random_entry}")

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Create Wiki Page
{% endblock %}

{% block body %}
<h1 class="mb-4">Create Wiki Page</h1>

<form action="{% url 'wiki_app:create' %}" method="POST">
   {% csrf_token %}
   {% for field in create_form %}
      <label class="h5" for="{{ field.auto_id }}">{{ field.label }}</label>
      {{ field }}
   {% endfor %}
   <button class="btn btn-primary ms-2" type="submit">Save New Wiki Page</button>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/create_error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Invalid search query
{% endblock %}

{% block body %}
   {% if  status == "exists"%}
      <p class="mx-auto mt-4 p-3 w-50 text-center border border-warning bg-warning-subtle rounded">Wiki Page for "{{ title }}" already exists <a href="/wiki/{{ title }}">({{ title }})</a></p>
   {% elif status == "invalid" %}
      <p class="mx-auto mt-4 p-3 w-50 text-center border border-warning bg-warning-subtle rounded">Invalid Wiki Page</p>
   {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Edit {{ title }}
{% endblock %}

{% block body %}
<h1 class="mb-4">Edit {{ title }} Wiki Page</h1>

<form action="{% url 'home:edit' title %}" method="POST">
   {% csrf_token %}
   {% for field in update_form %}
      <label class="h5" for="{{ field.auto_id }}">{{ field.label }}</label>
      {{ field }}
   {% endfor %}
   <button class="btn btn-primary ms-2" type="submit">Update {{ title }}</button>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1 class="mb-4">All Pages</h1>

    <ul class="list-inline list-group list-group-flush w-auto ms-3 me-4">
        {% for entry in entries %}
            <li>
                <div class="border border-primary-subtle rounded pt-2 pb-2 mb-2 link-primary row justify-content-between">
                    <div class="col-4">
                        <a href="wiki/{{ entry }}">{{ entry }}</a>
                    </div>
                    <div class="col-4 text-end">
                        <a class=""href="edit/{{ entry }}">Edit</a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/png" href="{% static 'encyclopedia/favicon.ico' %}"/>
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    </head>
    <body>
        
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2 class="mb-4">Wiki</h2>
                <form action="{% url 'wiki_app:search' %}" method="post">
                    {% csrf_token %}
                    {{ search_form }}
                </form>
                <div>
                    <a href="{% url 'home:index' %}" class="border border-primary-subtle rounded mb-3 list-group-item link-primary p-2 bold"><svg class="mb-1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                        <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
                    </svg> Home</a>
                </div>

                <div>
                    <a href="{% url 'home:create' %}" class="border border-primary-subtle rounded mb-2 list-group-item link-primary p-1 bold">
                        <svg class="mb-1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
                        </svg>
                        Create New Page
                    </a>
                </div>

                <div>
                    <a href="{% url 'home:random' %}" class="border border-primary-subtle rounded mb-2 list-group-item link-primary p-1 bold">
                        <svg class="mb-1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shuffle" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M0 3.5A.5.5 0 0 1 .5 3H1c2.202 0 3.827 1.24 4.874 2.418.49.552.865 1.102 1.126 1.532.26-.43.636-.98 1.126-1.532C9.173 4.24 10.798 3 13 3v1c-1.798 0-3.173 1.01-4.126 2.082A9.624 9.624 0 0 0 7.556 8a9.624 9.624 0 0 0 1.317 1.918C9.828 10.99 11.204 12 13 12v1c-2.202 0-3.827-1.24-4.874-2.418A10.595 10.595 0 0 1 7 9.05c-.26.43-.636.98-1.126 1.532C4.827 11.76 3.202 13 1 13H.5a.5.5 0 0 1 0-1H1c1.798 0 3.173-1.01 4.126-2.082A9.624 9.624 0 0 0 6.444 8a9.624 9.624 0 0 0-1.317-1.918C4.172 5.01 2.796 4 1 4H.5a.5.5 0 0 1-.5-.5z"/>
                            <path d="M13 5.466V1.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192zm0 9v-3.932a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192z"/>
                        </svg>
                        Random Page
                    </a>
                </div>

                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/no_search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   "{{ query }}" not found
{% endblock %}

{% block body %}
   <p class="mx-auto mt-4 p-3 w-50 text-center border border-warning bg-warning-subtle rounded">No results for "{{ query }}"</p>
{% endblock %}

encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Random
{% endblock %}

{% block body %}
   <p class="mx-auto mt-4 p-3 w-50 text-center border border-warning bg-warning-subtle rounded">Random.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/search_error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Invalid search query
{% endblock %}

{% block body %}
   <p class="mx-auto mt-4 p-3 w-50 text-center border border-warning bg-warning-subtle rounded">Invalid search query.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   Results for "{{ query }}"
{% endblock %}

{% block body %}
   <h1 class="mb-4">Results for "{{ query }}"</h1>
   
   <ul class="list-inline list-group list-group-flush w-auto ms-3 me-4">
      {% for match in matches %}
         <li><a class="border-primary-subtle rounded mb-2 list-group-item link-primary" href="wiki/{{ match }}">{{ match }}</a></li>
      {% endfor %}
   </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   {{ title }}
{% endblock %}

{% block body %}
   {{ content |safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/title_error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   "{{ title }}" not found
{% endblock %}

{% block body %}
   <p class="mx-auto mt-4 p-3 w-50 text-center border border-warning bg-warning-subtle rounded">Wiki for "{{ title }}" does not exist.</p>
{% endblock %}